#!/usr/bin/perl
#
# - ~/.latexmkrc
# - ~/.config/latexmk/latexmkrc
# - $XDG_CONFIG_HOME/latexmk/latexmkrc
#
# See latexmk(5) for more details.
#

# The default compiler.
$pdf_mode = 4;

# Compilers.
$latex = 'uplatex %O -shell-escape -halt-on-error -interaction=nonstopmode -file-line-error -synctex=1 -kanji=utf8 %S';
$lualatex = 'lualatex -shell-escape -halt-on-error -interaction=nonstopmode -file-line-error -synctex=1';

# Bibliographies.
$bibtex = 'upbibtex %O %B';
$biber = 'biber %O --bblencoding=utf8 -u -U --output_safechars %B';

# Miscs.
$dvipdf = 'dvipdfmx %O -o %D %S';

if ($^O eq 'darwin') {
  # If on macOS.
  $pdf_previewer = 'open -ga Skim';
} else {
  $pdf_previewer = 'zathura';
}
