language: shell

sudo: false

addons:
  apt:
    update: true
    packages:
      - git
      - tig
      - ctags
      - bash
      - vim
      - zsh
      - tmux

before_install:
  - make lint

install:
  - make install

