#!/usr/bin/env bash

set -eu

shopt -s dotglob
shopt -s nullglob

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}
XDG_CACHE_HOME=${XDG_CACHE_HOME:-~/.cache}
XDG_DATA_HOME=${XDG_DATA_HOME:-~/.local/share}

parent=$(cd "${0%/*}" && pwd)

readonly bin_srcpath=$parent/bin
readonly bin_dstpath=~/bin
readonly xdg_config_srcpath=$parent/xdg_config_home
readonly xdg_config_dstpath=$XDG_CONFIG_HOME
readonly home_config_srcpath=$parent/home
readonly home_config_dstpath=~

warning () {
  echo -e '\033[33m'"$*"'\033[0m' >&2
}

error () {
  echo -e '\033[31m'"$*"'\033[0m' >&2
}

# Make symbolik links from files in this repository to the destination directory.
#
# $1: the destination directory path
# $2...: dotfile paths in this repository.
links_to () {
  local -r destination_directory_path=$1
  shift

  while (( $# )); do
    local dotfile_path=$1
    shift

    local dotfile_basename=${dotfile_path##*/}
    local symbolic_link_destination_path=$destination_directory_path/$dotfile_basename

    if [[ -e $symbolic_link_destination_path ]]; then
      warning "Skip linking from $dotfile_path to $symbolic_link_destination_path because $dotfile_basename has already existed in $destination_directory_path."
    else
      command ln -sv "$dotfile_path" "$symbolic_link_destination_path"
    fi
  done
}

# Remove symbolic links poiint dotfiles in this repository from the destination directory.
#
# $1: the destination directory path
# $2...: dotfile paths in this repository.
unlinks_from () {
  local -r destination_directory_path=$1
  shift

  while (( $# )); do
    local dotfile_path=$1
    shift

    local dotfile_basename=${dotfile_path##*/}
    local symbolic_link_destination_path=$destination_directory_path/$dotfile_basename

    if [[ $dotfile_path -ef $symbolic_link_destination_path ]]; then
      command unlink "$symbolic_link_destination_path" && echo "unlink: $symbolic_link_destination_path"
    else
      warning "Skip unlinking $symbolic_link_destination_path because the file is not a symbolic link points a file in this repository."
    fi
  done
}

init () {
  mkdir -vp \
    ~/bin \
    "$XDG_CONFIG_HOME" \
    "$XDG_CACHE_HOME" \
    "$XDG_DATA_HOME" \
    ;
}

deploy () {
  links_to "$bin_dstpath" "$bin_srcpath"/*
  links_to "$xdg_config_dstpath" "$xdg_config_srcpath"/*
  links_to "$home_config_dstpath" "$home_config_srcpath"/*
}

undeploy () {
  unlinks_from "$bin_dstpath" "$bin_srcpath"/*
  unlinks_from "$xdg_config_dstpath" "$xdg_config_srcpath"/*
  unlinks_from "$home_config_dstpath" "$home_config_srcpath"/*
}

if ! (( $# )); then
  set -- --help
fi

while (( $# )); do
  case "$1" in
    --debug )
      set -x
      shift
      ;;
    -h | --help )
      echo -e -n "\
Descriptions:
  A dotfiles installer and uninstaller.

Usage:
  DOTFILES <SUBCOMMAND>

Subcommands:
  init         Initialize setup
  deploy       Deploy dotfiles
  undeploy     Remove deployed dotfiles

Options:
  -h, --help   Show this messages and exit.
"
      exit 0
      ;;
    init | deploy | undeploy )
      "$@"
      exit 0
      ;;
    * )
      error "An invalid argument '$1'"
      exit 1
      ;;
  esac
done
