#!/usr/bin/env bash

set -eu

shopt -s dotglob

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}

parent=$(cd "${0%/*}" && pwd)

readonly bin_srcpath=$parent/bin
readonly bin_dstpath=~/bin
readonly xdg_config_srcpath=$parent/xdg_config_home
readonly xdg_config_dstpath=$XDG_CONFIG_HOME
readonly home_config_srcpath=$parent/home
readonly home_config_dstpath=~

warning () {
  echo -e '\033[33m'"$*"'\033[0m' >&2
}

error () {
  echo -e '\033[31m'"$*"'\033[0m' >&2
}

# Make symbolic links that points to files passed as arguments under the destination directory.
#
# $1: the destination directory path
# $2...: filepaths
links_to () {
  local -r destination_directory_path=$1
  shift

  while (( $# )); do
    local filepath=$1
    shift

    local file_basename=${filepath##*/}
    local symbolic_link_destination_path=$destination_directory_path/$file_basename

    if [[ -e $symbolic_link_destination_path ]]; then
      warning "Skip linking from $filepath to $symbolic_link_destination_path because $file_basename has already existed in $destination_directory_path."
    else
      ln -sv "$filepath" "$symbolic_link_destination_path"
    fi
  done
}

# Remove symbolic links that points to files passed as arguments under the destination directory.
#
# $1: the destination directory path
# $2...: filepaths
unlinks_from () {
  local -r destination_directory_path=$1
  shift

  while (( $# )); do
    local filepath=$1
    shift

    local file_basename=${filepath##*/}
    local symbolic_link_destination_path=$destination_directory_path/$file_basename

    if [[ $filepath -ef $symbolic_link_destination_path ]]; then
      unlink "$symbolic_link_destination_path" && echo "unlink: $symbolic_link_destination_path"
    else
      warning "Skip unlinking $symbolic_link_destination_path because the file is not a symbolic link points a file in this repository."
    fi
  done
}

init () {
  mkdir -vp \
    "$bin_dstpath" \
    "$xdg_config_dstpath" \
    ;
}

deploy () {
  links_to "$bin_dstpath" "$bin_srcpath"/*
  links_to "$xdg_config_dstpath" "$xdg_config_srcpath"/*
  links_to "$home_config_dstpath" "$home_config_srcpath"/*
}

undeploy () {
  unlinks_from "$bin_dstpath" "$bin_srcpath"/*
  unlinks_from "$xdg_config_dstpath" "$xdg_config_srcpath"/*
  unlinks_from "$home_config_dstpath" "$home_config_srcpath"/*
}

if ! (( $# )); then
  set -- --help
fi

while (( $# )); do
  case "$1" in
    -h | --help )
      echo -n "\
Descriptions:
  A deployer/undeployer for dotfiles.

Usage:
  DOTFILES <SUBCOMMAND>

Subcommands:
  init         Make directories for dotfiles deploying.
  deploy       Make symbolic links points each dotfiles.
  undeploy     Unlink symbolic links points each dotfiles.

Options:
  -h, --help   Show this messages and exit.
"
      exit 0
      ;;
    init | deploy | undeploy )
      "$@"
      exit 0
      ;;
    * )
      error "An invalid argument '$1'"
      exit 1
      ;;
  esac
done
