#!/usr/bin/env bash

set -eu

shopt -s dotglob
shopt -s nullglob

warning () {
  echo -e '\033[33m'"$*"'\033[0m' >&2
}

error () {
  echo -e '\033[31m'"$*"'\033[0m' >&2
}

parent=$(cd "${0%/*}" && pwd)

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}
XDG_CACHE_HOME=${XDG_CACHE_HOME:-~/.cache}
XDG_DATA_HOME=${XDG_DATA_HOME:-~/.local/share}

readonly bin_srcpath="${parent}/bin"
readonly bin_dstpath=~/bin
readonly xdg_config_srcpath="${parent}/xdg_config_home"
readonly xdg_config_dstpath=$XDG_CONFIG_HOME
readonly home_config_srcpath="${parent}/home"
readonly home_config_dstpath=~

# Make symbolik links from files in source directory to in destination
# directory.
links () {
  local -r src_dir=$1
  local -r dst_dir=$2

  for link_src in "$src_dir"/*; do
    local f_base="${link_src##*/}"
    local link_dst="${dst_dir}/${f_base}"

    if [[ -e "${link_dst}" ]]; then
      warning "Skip linking from ${link_src} to ${link_dst} because ${f_base} has already existed in ${dst_dir}."
    else
      command ln -sv "$link_src" "$link_dst"
    fi
  done
}

# Remove symbolic links from destination directory.
unlinks () {
  local -r src_dir=$1
  local -r dst_dir=$2

  for link_src in "$src_dir"/*; do
    local f_base="${link_src##*/}"
    local link_dst="${dst_dir}/${f_base}"

    if ! [[ $link_src -ef $link_dst ]]; then
      warning "Skip unlinking $link_dst because the file is not a symbolic link points a file in this repository."
      continue
    fi

    command unlink "$link_dst" && echo "unlink: $link_dst"
  done
}

deploy () {
  links "$bin_srcpath" "$bin_dstpath"
  links "$xdg_config_srcpath" "$xdg_config_dstpath"
  links "$home_config_srcpath" "$home_config_dstpath"
}

undeploy () {
  unlinks "$bin_srcpath" "$bin_dstpath"
  unlinks "$xdg_config_srcpath" "$xdg_config_dstpath"
  unlinks "$home_config_srcpath" "$home_config_dstpath"
}

init () {
  mkdir -vp \
    ~/bin \
    "$XDG_CONFIG_HOME" \
    "$XDG_CACHE_HOME" \
    "$XDG_DATA_HOME" \
    ;
}

if ! (( $# )); then
  set -- --help
fi

while (( $# )); do
  case "$1" in
    --debug )
      set -x
      shift
      ;;
    -h | --help )
      echo -e -n "\
Descriptions:
  Dotfiles installer and uninstaller with extra.

Usage:
  INSTALL <SUBCOMMAND>

Subcommands:
  init         Initialize setup
  deploy       Deploy dotfiles
  undeploy     Remove deployed dotfiles

Options:
  -h, --help   Show this messages and exit.
"
      exit 0
      ;;
    init | deploy | undeploy )
      "$@"
      exit 0
      ;;
    * )
      error "An invalid argument '$1'"
      exit 1
      ;;
  esac
done
